import {
  Folder,
  Star,
  Heart,
  Zap,
  Target,
  Briefcase,
  Code,
  Palette,
  Coffee,
  Rocket,
  Globe,
  Camera,
  Music,
  Book,
  Settings,
  Users,
  Calendar,
  Mail,
  Phone,
  Home,
  Car,
  Plane,
  Ship,
  Train,
  Bike,
  Gamepad2,
  Trophy,
  Gift,
  Shield,
  Key,
  Bell,
  Flag,
  Tag,
  Bookmark,
  Archive,
  Database,
  Server,
  Cloud,
  Wifi,
  Battery,
  Monitor,
  Smartphone,
  Tablet,
  Headphones,
  Mic,
  Speaker,
  Video,
  FileText,
  Download,
  Upload,
  Filter,
  Edit,
  Trash,
  CheckCircle,
  AlertCircle,
  HelpCircle,
  MessageCircle,
  Sun,
  Moon,
  CloudRain,
  Leaf,
  Flower,
  Mountain,
  Waves,
  Clock,
  Timer,
  Watch,
  Hourglass,
  type LucideIcon,
  Search,
  Trees,
  Image,
  Lock,
} from "lucide-react";

export type IconOption = { name: string; component: LucideIcon };

export const projectIconsColors = [
  "#4F46E5", // Indigo
  "#059669", // Emerald
  "#DC2626", // Red
  "#7C3AED", // Violet
  "#EA580C", // Orange
  "#0891B2", // Cyan
  "#BE185D", // Pink
  "#65A30D", // Lime
  "#0F172A", // Slate
  "#92400E", // Amber
  "#1E40AF", // Blue
  "#166534", // Green
  "#991B1B", // Red Dark
  "#581C87", // Purple
  "#9A3412", // Orange Dark
  "#155E75", // Cyan Dark
];

// Fonction pour obtenir le nom de la couleur
export const getColorName = (color: string): string => {
  const colorNames: { [key: string]: string } = {
    "#4F46E5": "Indigo",
    "#059669": "Émeraude",
    "#DC2626": "Rouge",
    "#7C3AED": "Violet",
    "#EA580C": "Orange",
    "#0891B2": "Cyan",
    "#BE185D": "Rose",
    "#65A30D": "Vert lime",
    "#0F172A": "Ardoise",
    "#92400E": "Ambre",
    "#1E40AF": "Bleu",
    "#166534": "Vert",
    "#991B1B": "Rouge foncé",
    "#581C87": "Violet foncé",
    "#9A3412": "Orange foncé",
    "#155E75": "Cyan foncé",
  };
  return colorNames[color] || color;
};

export const projectIcons: IconOption[] = [
  { name: "Folder", component: Folder },
  { name: "Star", component: Star },
  { name: "Heart", component: Heart },
  { name: "Zap", component: Zap },
  { name: "Target", component: Target },
  { name: "Briefcase", component: Briefcase },
  { name: "Code", component: Code },
  { name: "Palette", component: Palette },
  { name: "Coffee", component: Coffee },
  { name: "Rocket", component: Rocket },
  { name: "Globe", component: Globe },
  { name: "Camera", component: Camera },
  { name: "Music", component: Music },
  { name: "Book", component: Book },
  { name: "Settings", component: Settings },
  { name: "Users", component: Users },
  { name: "Calendar", component: Calendar },
  { name: "Mail", component: Mail },
  { name: "Phone", component: Phone },
  { name: "Home", component: Home },
  { name: "Car", component: Car },
  { name: "Plane", component: Plane },
  { name: "Ship", component: Ship },
  { name: "Train", component: Train },
  { name: "Bike", component: Bike },
  { name: "Gamepad2", component: Gamepad2 },
  { name: "Trophy", component: Trophy },
  { name: "Gift", component: Gift },
  { name: "Shield", component: Shield },
  { name: "Key", component: Key },
  { name: "Lock", component: Lock },
  { name: "Bell", component: Bell },
  { name: "Flag", component: Flag },
  { name: "Tag", component: Tag },
  { name: "Bookmark", component: Bookmark },
  { name: "Archive", component: Archive },
  { name: "Database", component: Database },
  { name: "Server", component: Server },
  { name: "Cloud", component: Cloud },
  { name: "Wifi", component: Wifi },
  { name: "Battery", component: Battery },
  { name: "Monitor", component: Monitor },
  { name: "Smartphone", component: Smartphone },
  { name: "Tablet", component: Tablet },
  { name: "Headphones", component: Headphones },
  { name: "Mic", component: Mic },
  { name: "Speaker", component: Speaker },
  { name: "Video", component: Video },
  { name: "Image", component: Image },
  { name: "FileText", component: FileText },
  { name: "Download", component: Download },
  { name: "Upload", component: Upload },
  { name: "Search", component: Search },
  { name: "Filter", component: Filter },
  { name: "Edit", component: Edit },
  { name: "Trash", component: Trash },
  { name: "CheckCircle", component: CheckCircle },
  { name: "AlertCircle", component: AlertCircle },
  { name: "HelpCircle", component: HelpCircle },
  { name: "MessageCircle", component: MessageCircle },
  { name: "Sun", component: Sun },
  { name: "Moon", component: Moon },
  { name: "CloudRain", component: CloudRain },
  { name: "Leaf", component: Leaf },
  { name: "Flower", component: Flower },
  { name: "Tree", component: Trees },
  { name: "Mountain", component: Mountain },
  { name: "Waves", component: Waves },
  { name: "Clock", component: Clock },
  { name: "Timer", component: Timer },
  { name: "Watch", component: Watch },
  { name: "Hourglass", component: Hourglass },
];
